name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  application:
    uses: codbex/codbex-infra/.github/workflows/application-release.yaml@main
    with:
      application-name: codbex-jason
      install-dependencies: true
      dockerfile-location: application/
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-jason - ${{ inputs.release-version }}
  
        Customer Management Application
  
        ## Deployment
  
        ```
        docker run --name codbex-jason \
        --rm -p 80:80 \
        ghcr.io/codbex/codbex-jason:${{ inputs.release-version }}
        ```

        ### Sample Data

        ```
        docker run --name codbex-jason-data-sample \
        --rm -p 80:80 \
        ghcr.io/codbex/codbex-jason-data-sample:${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-jason/gen/](http://localhost:80/services/web/codbex-jason/gen/) - Admin Panel
    secrets: inherit
  application-data-sample:
    uses: codbex/codbex-infra/.github/workflows/application-release.yaml@main
    with:
      application-name: codbex-jason-data-sample
      install-dependencies: true
      dockerfile-location: application-data-sample/
      release-version: ${{ inputs.release-version }}
      release-create-branch: false
    secrets: inherit
  deploy:
    needs: [application, application-data-sample]
    uses: ./.github/workflows/deploy.yaml
    with:
      application-version: ${{ inputs.release-version }}
    secrets: inherit